os: linux
dist: trusty
language: android

before_install:
  - yes | sdkmanager "build-tools;30.0.2"
  - yes | sdkmanager "platforms;android-30"

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build

deploy:
  provider: script
  script: ./gradlew :core:bintrayUpload :android:bintrayUpload :androidx-fragment:bintrayUpload :androidx-viewmodel:bintrayUpload :androidx-viewmodel-savedstate:bintrayUpload
  skip_cleanup: true
  on:
    branch: main
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
