name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Test
        run: ./gradlew test

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew publishAllPublicationsToOssStagingRepository
          ./gradlew closeAndReleaseRepository
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - uses: actions/upload-artifact@v2
        with:
          path: |
            **/build/libs/*.jar
            **/build/outputs/apk/**/*.apk
            **/build/outputs/bundle/**/*.aab
